Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,5 +12,23 @@ jobs:
     steps:
       - name: checkout Code
         uses: actions/checkout@v3
-
-        
+      - name: Check if files exist
+        run: |
+            if [ -f index.html ]; then
+              echo "index.html found ✅"
+            else
+              echo "index.html not found ❌"
+              exit 1
+            fi
+            if [ -f styles.css ]; then
+              echo "styles.css found ✅"
+            else
+              echo "styles.css not found ❌"
+              exit 1
+            fi
+            if [ -f script.js ]; then
+              echo "script.js found ✅"
+            else
+              echo "script.js not found ❌"
+              exit 1
+            fi        
